import streamlit as st
import pandas as pd
from mitosheet.streamlit.v1 import spreadsheet

# Start with an empty DataFrame
data = pd.DataFrame()

# Allow user to upload a CSV file
uploaded_file = st.file_uploader("Choose a CSV file", type='csv')

if uploaded_file is not None:
    data = pd.read_csv(uploaded_file)

# Create a Mito sheet in the Streamlit app and get the code generated by user interactions with the sheet
sheet, code = spreadsheet(data)

# Display the generated code in real-time below the sheet
st.code(code)

# Add a download button for the generated code 
st.download_button(
    label="Download Python Code",
    data=code,
    file_name="mito_generated_code.py",
    mime="text/x-python"
)
